# Generated by Django 4.2.9 on 2024-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dec', models.TextField()),
                ('img', models.ImageField(upload_to='student_img/')),
            ],
        ),
    ]
